POST http://localhost:4600/api/registerOwner
Content-Type: application/json

{

    "first_name": "test",
    "last_name": "gol",
    "cin": "ha134567",
    "email": "owner@gmail.com",
    "rib": "123456789009876543211234",
    "phone": "0601181312",
    "password": "123ABC"
}
###
POST http://localhost:4600/api/registerClient
Content-Type: application/json

{

    "first_name": "test",
    "last_name": "gol",
    "cin": "ha134567",
    "email": "good@gmail.com",
    "phone": "0601181312",
    "password": "azerty"
   
}
###
GET http://localhost:4600/api/login
Content-Type: application/json

{

    "email": "owner@gmail.com",
    "password": "azerty"
   
}
###
GET http://localhost:4600/api/login
Content-Type: application/json

{

    "email": "owner@gmail.com",
    "password": "123ABC"
   
}
###
POST http://localhost:4600/api/addcar
Content-Type: application/json

{
    "registration_number": "6564365",
    "name": "skoda2",
    "image": "myphoto1.png",
    "mark": "2019",
    "color": "red",
    "price": "654564",
    "fuel": "essence"
}

###
GET http://localhost:4600/api/logout
###
GET http://localhost:4600/api/cars
auth_token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNmRjMzQyY2M5ZDRkNWNiODdiMDg0MiIsInJvbGUiOiJjbGllbnQiLCJpYXQiOjE2MTc4MTA3MjEsImV4cCI6MTYxNzgxMTMyMX0.xUWKRFjN3j0GKw5I2aJ1AOBzb34nUvF82EtBoMY9P54